services:
  redis:
    image: redis:6-alpine
    container_name: redis-limiter
    ports:
      - "6379:6379"

  node_app:
    build: .
    container_name: node-rate-limiter
    ports:
      - "8000:8000"
    depends_on:
      - redis