console.log('Executando day003.js');
console.error('Erro ao executar day003.js');
console.warn('Cuidado ao executar day003.js');
console.info('Informação ao executar day003.js');
console.debug('Debugando day003.js');
console.trace('Traçando day003.js');
console.group('Grupo de logs');
console.log('Log 1');
console.log('Log 2');
console.groupEnd();
console.time('Tempo de execução');
console.timeEnd('Tempo de execução');
console.table(['item1', 'item2', 'item3']);
console.assert(1 === 2, 'Erro de assert');
console.count('count');
console.count('count');
console.count('count');
console.count('count');
console.count('count');
console.countReset('count');
console.log('Fim da execução de day003.js');